local M={};MWDT.RegisterModule("texture",M)
MWDT.RegisterTab("texture","Textures",function(p)
 local h=MWDT.MakeLabel(p,"Searchable Texture Catalog",15);h:SetPoint("TOPLEFT",8,-8)
 local path=MWDT.MakeEditBox(p,false);path:SetPoint("TOPLEFT",8,-34);path:SetWidth(390);path:SetHeight(22);path:SetText("Interface\\Icons\\INV_Misc_QuestionMark");MWDT.AttachEditBoxBG(path)
 local preview=MWDT.MakeButton(p,"Preview",72,22);preview:SetPoint("LEFT",path,"RIGHT",8,0);local clear=MWDT.MakeButton(p,"Clear",58,22);clear:SetPoint("LEFT",preview,"RIGHT",6,0)
 local candidate=MWDT.MakeButton(p,"BGRA8 Candidate",105,22);candidate:SetPoint("TOPLEFT",8,-66)
 local comparison=MWDT.MakeButton(p,"Palette Control",105,22);comparison:SetPoint("LEFT",candidate,"RIGHT",6,0)
 local inspect=MWDT.MakeButton(p,"Inspect BLP2",90,22);inspect:SetPoint("LEFT",comparison,"RIGHT",6,0)
 local traceStatus=MWDT.MakeButton(p,"Trace Status",100,22);traceStatus:SetPoint("LEFT",inspect,"RIGHT",6,0)
 local dxt1=MWDT.MakeButton(p,"DXT1 Control",90,22);dxt1:SetPoint("TOPLEFT",8,-98)
 local dxt3=MWDT.MakeButton(p,"DXT3 Control",90,22);dxt3:SetPoint("LEFT",dxt1,"RIGHT",6,0)
 local dxt5=MWDT.MakeButton(p,"DXT5 Control",90,22);dxt5:SetPoint("LEFT",dxt3,"RIGHT",6,0)
 local offline=MWDT.MakeButton(p,"Offline BGRA->DXT5",155,22);offline:SetPoint("LEFT",dxt5,"RIGHT",6,0)
 local traceDXT5=MWDT.MakeButton(p,"TRACE DXT5",110,22);traceDXT5:SetPoint("TOPLEFT",8,-130)
 local traceBGRA8=MWDT.MakeButton(p,"TRACE BGRA8",110,22);traceBGRA8:SetPoint("LEFT",traceDXT5,"RIGHT",6,0)
 local traceRefresh=MWDT.MakeButton(p,"Native Trace Status",150,22);traceRefresh:SetPoint("LEFT",traceBGRA8,"RIGHT",6,0)
 local search=MWDT.MakeEditBox(p,false);search:SetPoint("TOPLEFT",8,-162);search:SetWidth(230);search:SetHeight(22);MWDT.AttachEditBoxBG(search)
 local find=MWDT.MakeButton(p,"Search",65,22);find:SetPoint("LEFT",search,"RIGHT",8,0);local prev=MWDT.MakeButton(p,"Previous",70,22);prev:SetPoint("LEFT",find,"RIGHT",6,0);local nextb=MWDT.MakeButton(p,"Next",55,22);nextb:SetPoint("LEFT",prev,"RIGHT",6,0)
 local box=CreateFrame("Frame",nil,p);box:SetPoint("TOPLEFT",8,-198);box:SetWidth(300);box:SetHeight(300);box:SetBackdrop({bgFile="Interface\\Tooltips\\UI-Tooltip-Background",edgeFile="Interface\\Tooltips\\UI-Tooltip-Border",tile=true,tileSize=16,edgeSize=12,insets={left=3,right=3,top=3,bottom=3}})
 local tex=box:CreateTexture(nil,"ARTWORK");tex:SetPoint("TOPLEFT",8,-8);tex:SetPoint("BOTTOMRIGHT",-8,8)
 local info=MWDT.MakeScrollText(p);info:SetPoint("TOPLEFT",330,-198);info:SetPoint("BOTTOMRIGHT",-18,8)
 local matches,index={},0
 local function show(i) if #matches==0 then info.editBox:SetText("No catalog matches. Catalog size: "..#(MWDT_TEXTURE_CATALOG or {}));return end;if i<1 then i=#matches elseif i>#matches then i=1 end;index=i;local r=matches[i];path:SetText(r[1]);info.editBox:SetText(i.." / "..#matches.."\nPath: "..r[1].."\nName: "..r[2].."\nCategory: "..r[3].."\nSource: "..r[5].."\nPress Preview to load explicitly.") end
 find:SetScript("OnClick",function() matches={};local q=string.lower(search:GetText() or "");for i=1,#(MWDT_TEXTURE_CATALOG or {}) do local r=MWDT_TEXTURE_CATALOG[i];if q=="" or string.find(string.lower(r[1]),q,1,true) then matches[#matches+1]=r end end;show(1) end)
 prev:SetScript("OnClick",function()show(index-1)end);nextb:SetScript("OnClick",function()show(index+1)end)
 preview:SetScript("OnClick",function()tex:SetTexture(path:GetText());info.editBox:SetText("Preview requested explicitly:\n"..path:GetText())end);clear:SetScript("OnClick",function()tex:SetTexture(nil)end)
 candidate:SetScript("OnClick",function()local v="Interface\\MasterWoW\\BLP2Test";path:SetText(v);tex:SetTexture(nil);local armed=false;if type(TBCExt_ArmBLPObservation)=="function" then local ok,r=pcall(TBCExt_ArmBLPObservation);armed=ok and r==true end;tex:SetTexture(v);local status="Observation API unavailable";if type(TBCExt_GetBLPObservationStatus)=="function" then local ok,r=pcall(TBCExt_GetBLPObservationStatus);if ok then status=tostring(r) end end;info.editBox:SetText("Original BGRA8 requested through stock Texture:SetTexture().\nObservation armed: "..tostring(armed).."\n"..status.."\nRuntime byte replacement: DISABLED.")end)
 traceStatus:SetScript("OnClick",function()if type(TBCExt_GetBLPObservationStatus)~="function" then info.editBox:SetText("Observation API unavailable; use DLL 0.1.6 research build.");return end;local ok,r=pcall(TBCExt_GetBLPObservationStatus);info.editBox:SetText(ok and tostring(r) or ("Observation status error: "..tostring(r)))end)
 local function nativeStatus(prefix) if type(TBCExt_GetNativeBLPTraceStatus)~="function" then info.editBox:SetText(prefix.."\nNative correlation API unavailable; DLL not built/copied.");return end;local ok,r=pcall(TBCExt_GetNativeBLPTraceStatus);info.editBox:SetText(prefix.."\n"..(ok and tostring(r) or ("Trace status error: "..tostring(r)))) end
 local function runNativeTrace(label,v,armName)
  path:SetText(v);tex:SetTexture(nil)
  local arm=_G[armName];if type(arm)~="function" then nativeStatus(label.." | ARM API UNAVAILABLE");return end
  local ok,armed=pcall(arm);if not ok or armed~=true then nativeStatus(label.." | ARM FAILED");return end
  tex:SetTexture(v);nativeStatus(label.." | STOCK REQUEST SENT")
 end
 traceDXT5:SetScript("OnClick",function()runNativeTrace("TRACE DXT5","Interface\\MasterWoW\\TBCExt_BLP2Test_OfflineDXT5","TBCExt_ArmNativeBLPDXT5")end)
 traceBGRA8:SetScript("OnClick",function()runNativeTrace("TRACE BGRA8","Interface\\MasterWoW\\BLP2Test","TBCExt_ArmNativeBLPBGRA8")end)
 traceRefresh:SetScript("OnClick",function()nativeStatus("NATIVE TRACE STATUS")end)
 comparison:SetScript("OnClick",function()local v="Interface\\MasterWoW\\BLP2Palette";path:SetText(v);tex:SetTexture(v);info.editBox:SetText("Paletted BLP2 control requested through the same stock Texture path.\nExpected: colored 64x64 checker.")end)
 local function stockDXT(name) local v="Interface\\MasterWoW\\TBCExt_"..name;path:SetText(v);tex:SetTexture(nil);tex:SetTexture(v);info.editBox:SetText(name.." BLP2 control requested through stock Texture:SetTexture().\nRuntime transform: DISABLED.\nRecord PASS or FAIL; do not infer success from an old preview.")end
 dxt1:SetScript("OnClick",function()stockDXT("DXT1")end);dxt3:SetScript("OnClick",function()stockDXT("DXT3")end);dxt5:SetScript("OnClick",function()stockDXT("DXT5")end)
 offline:SetScript("OnClick",function()local v="Interface\\MasterWoW\\TBCExt_BLP2Test_OfflineDXT5";path:SetText(v);tex:SetTexture(nil);tex:SetTexture(v);info.editBox:SetText("OFFLINE-converted copy requested through stock Texture:SetTexture().\nOn-disk original BGRA8 candidate remains unchanged.\nRuntime byte replacement: DISABLED.\nRecord PASS or FAIL for this separate file only.")end)
 inspect:SetScript("OnClick",function()if type(TBCExt_InspectBLP)~="function" then info.editBox:SetText("TBCExt_InspectBLP is unavailable. DLL/API 5 is not active.");return end;local ok,text=pcall(TBCExt_InspectBLP,"TBCExt_BLP2Test.blp");info.editBox:SetText(ok and tostring(text) or ("Inspector error: "..tostring(text)))end)
end)
