#include "Graphics/Textures/BLPReader.hpp"
#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <string>
#include <tuple>
#include <vector>
namespace fs=std::filesystem;
namespace {
uint32_t U32(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
bool Pow2(uint32_t v){return v&&!(v&(v-1));}
std::vector<uint8_t> Read(const fs::path&p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)return{};auto n=f.tellg();if(n<=0||uint64_t(n)>512ull*1024*1024)return{};std::vector<uint8_t>b(size_t(n));f.seekg(0);return f.read((char*)b.data(),n)?b:std::vector<uint8_t>{};}
struct Mip{uint32_t w,h,off,size;uint64_t expected;bool valid;};
struct Record{fs::path path;std::string magic="UNKNOWN",version="UNKNOWN",storage="UNKNOWN",compat="MALFORMED",reason;unsigned enc=0,depth=0,alpha=0;size_t mipCount=0;bool parsed=false,candidate=false,exact=false;std::vector<Mip>mips;};
Record Analyze(const fs::path&p){Record r;r.path=p;auto data=Read(p);if(data.size()<4){r.reason="unreadable or shorter than magic";return r;}r.magic.assign((char*)data.data(),4);auto x=Blp::Read(data.data(),data.size());if(!x.ok){r.compat=x.error.rfind("Unsupported",0)==0?"UNSUPPORTED":"MALFORMED";r.reason=x.error;return r;}r.parsed=true;auto&t=x.texture;r.version=Blp::Name(t.version);r.storage=Blp::Name(t.sourceFormat);r.enc=t.encoding;r.depth=t.alphaDepth;r.alpha=t.alphaEncoding;r.mipCount=t.mipLevels.size();bool layout=t.version==Blp::Version::BLP2&&data.size()>=148&&!t.mipLevels.empty(),ended=false;uint32_t w=t.width,h=t.height;uint64_t priorEnd=148;
 if(t.version==Blp::Version::BLP2&&data.size()>=148)for(size_t i=0;i<16;++i){uint32_t o=U32(data.data()+20+i*4),s=U32(data.data()+84+i*4);if(!o||!s){if(o!=s)layout=false;ended=true;continue;}uint64_t expected=uint64_t(w)*h*4,end=uint64_t(o)+s;bool valid=!ended&&expected<=UINT32_MAX&&s==expected&&o>=148&&end<=data.size()&&o>=priorEnd&&i<t.mipLevels.size()&&t.mipLevels[i].width==w&&t.mipLevels[i].height==h;r.mips.push_back({w,h,o,s,expected,valid});layout&=valid;priorEnd=end;w=std::max(1u,w/2);h=std::max(1u,h/2);}layout=layout&&r.mips.size()==t.mipLevels.size()&&(r.mips.size()<=1||data[11]!=0);
 r.candidate=t.version==Blp::Version::BLP2&&t.encoding==3&&t.alphaDepth==8&&t.alphaEncoding==0&&Pow2(t.width)&&Pow2(t.height)&&t.width<1024&&t.height<1024&&layout;std::string leaf=p.filename().string();std::transform(leaf.begin(),leaf.end(),leaf.begin(),[](unsigned char c){return char(std::tolower(c));});r.exact=r.candidate&&(leaf=="tbcext_blp2test.blp"||leaf=="blp2test.blp")&&t.width==64&&t.height==64&&t.mipLevels.size()==1;
 if(r.exact)r.compat="NATIVE_BGRA_1_2_RUNTIME_VERIFIED_EXACT_CONTROL";else if(r.candidate)r.compat="NATIVE_BGRA_1_2_STRUCTURAL_CANDIDATE";else if(t.version==Blp::Version::BLP1||t.encoding==1||t.encoding==2)r.compat="STOCK_TBC_SUPPORTED";else if(t.encoding==3)r.compat="TBCEXT_DECODE_ONLY";else r.compat="UNKNOWN";r.reason=r.candidate?"BLP2 encoding 3; alpha 8/0; valid power-of-two dimensions; dense, in-bounds, non-overlapping width*height*4 mip payloads":t.encoding==3?"encoding-3 metadata/layout is outside the justified native 1/2 candidate contract":"format belongs to an established stock family";return r;}
void Print(const Record&r){std::cout<<"PATH: "<<r.path.string()<<"\nMAGIC: "<<r.magic<<'\n';if(!r.parsed){std::cout<<"COMPATIBILITY: "<<r.compat<<"\nREASON: "<<r.reason<<"\n\n";return;}std::cout<<"VERSION: "<<r.version<<"\nMIP COUNT: "<<r.mipCount<<"\nENCODING: "<<r.enc<<"\nALPHA: "<<r.depth<<'/'<<r.alpha<<"\nSOURCE FORMAT: "<<r.storage<<'\n';for(size_t i=0;i<r.mips.size();++i){auto&m=r.mips[i];std::cout<<"MIP "<<i<<"\n  "<<m.w<<'x'<<m.h<<"\n  offset "<<m.off<<"\n  declared "<<m.size<<"\n  expected "<<m.expected<<"\n  RAW BGRA VALID "<<(m.valid?"YES":"NO")<<'\n';}std::cout<<"NATIVE CANDIDATE: "<<(r.candidate?"YES":"NO")<<"\nCOMPATIBILITY: "<<r.compat<<"\nREASON: "<<r.reason<<"\nCONFIDENCE: "<<(r.exact?"VERIFIED_RUNTIME exact owner control":r.candidate?"CONTROLLED_STRUCTURAL_CANDIDATE; owner runtime pending":"VERIFIED_STATIC classifier")<<"\n\n";}
struct Summary{size_t files=0;std::map<std::string,size_t>magic,storage,compat,mips;std::map<std::tuple<unsigned,unsigned,unsigned>,size_t>modes;std::map<std::string,std::vector<std::string>>reps;void Add(const Record&r){++files;++magic[r.magic];++storage[r.storage];++compat[r.compat];++modes[{r.enc,r.depth,r.alpha}];++mips[r.mipCount<=1?"1":r.mipCount<=4?"2-4":r.mipCount<=8?"5-8":"9-16"];if(r.compat!="STOCK_TBC_SUPPORTED"&&reps[r.compat].size()<5)reps[r.compat].push_back(r.path.string());}void Print()const{std::cout<<"CORPUS SUMMARY\nFILES: "<<files<<'\n';auto g=[](const char*t,const auto&m){std::cout<<t<<":\n";for(auto&[k,v]:m)std::cout<<"  "<<k<<": "<<v<<'\n';};g("MAGIC/VERSION",magic);g("SOURCE STORAGE",storage);g("MIP COUNT CATEGORY",mips);g("COMPATIBILITY",compat);std::cout<<"ENCODING/ALPHA:\n";for(auto&[k,v]:modes)std::cout<<"  "<<std::get<0>(k)<<'/'<<std::get<1>(k)<<'/'<<std::get<2>(k)<<": "<<v<<'\n';for(auto&[c,ps]:reps){std::cout<<"REPRESENTATIVE "<<c<<":\n";for(auto&p:ps)std::cout<<"  "<<p<<'\n';}}};
}
int main(int argc,char**argv){if(argc<2){std::cerr<<"usage: blp_classify [--summary] <file-or-directory> [...]\n";return 2;}bool summaryOnly=false;std::vector<fs::path>files;for(int i=1;i<argc;++i){if(std::string(argv[i])=="--summary"){summaryOnly=true;continue;}fs::path in(argv[i]);std::error_code e;if(fs::is_directory(in,e)){for(fs::recursive_directory_iterator it(in,e),end;!e&&it!=end;it.increment(e))if(it->is_regular_file()&&it->path().extension()==".blp")files.push_back(it->path());}else files.push_back(in);}std::sort(files.begin(),files.end());Summary s;for(auto&p:files){auto r=Analyze(p);s.Add(r);if(!summaryOnly)Print(r);}if(summaryOnly)s.Print();return 0;}
